const data = [
  {
    id: 1,
    title: "Cookie",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Cookies.jpg",
    numberInStock: 1,
    price: 1.24,
  },
  {
    id: 2,
    title: "Cake",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Cake.jpg",
    numberInStock: 1,
    price: 2.5,
  },
  {
    id: 3,
    title: "Coffee",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Coffee.jpg",
    numberInStock: 1,
    price: 3.45,
  },
  {
    id: 4,
    title: "Danish",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Danish.jpg",
    numberInStock: 1,
    price: 0.5,
  },
  {
    id: 5,
    title: "Desserts",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Desserts.jpg",
    numberInStock: 1,
    price: 4.5,
  },
  {
    id: 6,
    title: "Feeter Pies",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Feeter-pies.jpg",
    numberInStock: 1,
    price: 1.2,
  },
  {
    id: 7,
    title: "Flat Bread",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Flat-Bread.jpg",
    numberInStock: 1,
    price: 0.35,
  },
  {
    id: 8,
    title: "Muffin",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Muffin.jpg",
    numberInStock: 1,
    price: 1.5,
  },
  {
    id: 9,
    title: "Pice Cake",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Pice-Cake.jpg",
    numberInStock: 1,
    price: 3.0,
  },
  {
    id: 10,
    title: "Soft Bread",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Soft-Bread.jpg",
    numberInStock: 1,
    price: 0.3,
  },
  {
    id: 11,
    title: "Toast",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Toast.jpg",
    numberInStock: 1,
    price: 0.5,
  },
  {
    id: 12,
    title: "Toast Bread",
    description: "A cookie is a baked or cooked food",
    image: "/assets/images/Toast-Bread.jpg",
    numberInStock: 1,
    price: 0.8,
  },
];
export default data;
